version: '3.8'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data

  arkose-token-service:
    image: wizerd/generate-arkose:latest
    ports:
      - "23888:8080"
    volumes:
      - ./harPool:/harPool
    environment:
      - MIN_TOKEN_COUNT=5  # Arkose Token池中的最小Token数量
      - TOKEN_EXPIRY_MINUTES=25  # Arkose Token的有效期，单位为分钟
    depends_on:
      - redis  # 确保在应用服务启动前 Redis 服务已经运行
